# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatwitter', '0002_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='/datatwitter/files/%f')),
            ],
        ),
    ]
