# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 12:17
from __future__ import unicode_literals

import datatwitter.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatwitter', '0005_auto_20160215_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.TextField(default='Untitled', max_length=100)),
                ('file_path', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/datatwitter/files/'), upload_to=datatwitter.models.Dataset.content_name)),
            ],
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
