# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatwitter', '0007_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='polarity',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='subjecivity',
            field=models.BigIntegerField(),
        ),
    ]
